package view.admin;

import controller.FileController;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modal.Customer;
import modal.Order;
import modal.OrderDetail;
import modal.product;
/**
 *
 * @author Kien Ninh
 */
public class ManagementOrderDetail extends javax.swing.JFrame {

    /**
     * Creates new form ManagementOrderDetail
     */
    
    
    public  ManagementOrderDetail(String mahd,String makh, String ngay) {
        
       initComponents();
       ipnorderID.setText(mahd);
       ipnorderID.setText(makh);
       ipnDate.setText(ngay);
       ipnTotal.setText(Tongtien+"");
       ProductDisplay();
       OrderDetailDisplay(); 
       
       }

    private ManagementOrderDetail() {
        initComponents();
        ProductDisplay();
        OrderDetailDisplay(); 
        ipnTotal.setText(Tongtien+"");
    }
   
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
             new ManagementOrderDetail().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ipnProductID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ipnPrice = new javax.swing.JTextField();
        ipnMoney = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ipnQuantity = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderDetailTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ipnDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ipnorderID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ipnTotal = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        productTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        ipnCustomerID1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel7.setText("Chi tiết hóa đơn");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hóa đơn"));

        ipnProductID.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        ipnProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipnProductIDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel5.setText("Mã sản phẩm");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel6.setText("Số lượng");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel8.setText("Thành tiền");

        ipnPrice.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N

        ipnMoney.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        ipnMoney.setEnabled(false);

        addBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addBtn.setText("Thêm ");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updateBtn.setText("Sửa ");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deleteBtn.setText("Xóa");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel9.setText("Giá bán");

        ipnQuantity.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(addBtn)
                                .addGap(62, 62, 62)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(ipnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ipnProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ipnMoney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ipnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipnProductID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ipnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ipnMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ipnPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addGap(132, 132, 132))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 470, 200));

        orderDetailTbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        orderDetailTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderDetailTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderDetailTblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(orderDetailTbl);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 470, 200));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Ngày tạo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 20));

        ipnDate.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(ipnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 170, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Mã hóa đơn");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Mã khách hàng");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 20));

        ipnorderID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(ipnorderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 170, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Tổng tiền");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 20));

        ipnTotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(ipnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, -1));

        productTbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        productTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Giảm giá", "Số lượng còn"
            }
        ));
        productTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTblMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(productTbl);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 410, 200));

        jButton1.setText("Thoát");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, 40));

        ipnCustomerID1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(ipnCustomerID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static DefaultTableModel model;
    static DefaultTableModel modelPro;
    float Tongtien=TotalOrder();
    List<OrderDetail> orderDetails=new ArrayList<>();
    List<Customer> customers=new ArrayList<>();
    List<Order> orders =new ArrayList<>();
    List<product> products=new ArrayList<>();
    static FileController fileController;
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        
        float SaleOff=(float) 0.0;
        Integer ProductID=Integer.parseInt(ipnProductID.getText());
        float Price=Float.parseFloat(ipnPrice.getText());
        Integer Quantity=Integer.parseInt(ipnQuantity.getText());
        for(product a:products){
            if(a.getmaSP().equals(ProductID))
            {
                SaleOff=a.getGiamGia();
            }
            
        }
        float Money=tinhtongTien(Quantity, Price, SaleOff,true);
        Integer OrderID=Integer.parseInt(ipnorderID.getText());
        ipnMoney.setText(Money+"");
        OrderDetail od=new OrderDetail(OrderID,ProductID,Quantity);
        orderDetails.add(od);
        fileController.updateListOrderDetail("orderDedtail.txt", orderDetails);
        model.addRow(new Object[]{
            OrderID,ProductID,Quantity,Money
        }
        );
        
       ipnTotal.setText(Tongtien+"");
        setNullIPN();
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        float SaleOff=(float) 0.0;
        Integer ProductID=Integer.parseInt(ipnProductID.getText());
        float Price=Float.parseFloat(ipnPrice.getText());
        Integer Quantity=Integer.parseInt(ipnQuantity.getText());
        for(product a:products){
            if(a.getmaSP().equals(ProductID))
            {
                SaleOff=a.getGiamGia();
            }
            
        float Money=tinhtongTien(Quantity, Price, SaleOff,true);
        Integer OrderID=Integer.parseInt(ipnorderID.getText());
        ipnMoney.setText(Money+"");
        OrderDetail od=new OrderDetail(OrderID,ProductID,Quantity);
        orderDetails.add(od);
        fileController.writeOrderDetailToFile("orderDedtail.txt", od);
        model.addRow(new Object[]{
            OrderID,ProductID,Quantity,Money
        }
        );
       ipnTotal.setText(Tongtien+"");
       setNullIPN();
        }
    }//GEN-LAST:event_addBtnActionPerformed
    private void orderDetailTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderDetailTblMouseClicked
        //hiển thị bảng chi tiết hóa đơn
        int row=orderDetailTbl.getSelectedRow();
        Integer ProductID=(Integer)orderDetailTbl.getValueAt(row, 0);
        Integer quantity=(Integer)orderDetailTbl.getValueAt(row, 1);
        float Money=(Float)orderDetailTbl.getValueAt(row, 2);
         //sdet dữ liệu lên ô text
        ipnProductID.setText(ProductID+"");
        for(product a:products){
            if(a.getmaSP().equals(ProductID)){
                ipnPrice.setText(a.getGiaBan()+"");
            }    
        }
        ipnMoney.setText(Money+"");
        ipnQuantity.setText(quantity+"");
        
    }//GEN-LAST:event_orderDetailTblMouseClicked

    private void ipnProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipnProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipnProductIDActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int row=orderDetailTbl.getSelectedRow();
        Integer ProductID=(Integer)orderDetailTbl.getValueAt(row, 0);
        Integer Quantity=(Integer)orderDetailTbl.getValueAt(row, 1);
        float Money=(Float)orderDetailTbl.getValueAt(row, 2);
        Integer OrderID=Integer.parseInt(ipnorderID.getText());
        OrderDetail od=new OrderDetail(OrderID,ProductID,Quantity);
        for(OrderDetail item:orderDetails){
            if(od.equals(item)){
                orderDetails.remove(item);
                break;
            }
                
        }
       ipnTotal.setText(Tongtien+"");
        setNullIPN();
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
//        System.exit(0);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void productTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTblMouseClicked
              int row=productTbl.getSelectedRow();
              Integer productID=(Integer)modelPro.getValueAt(row,0);
              float  Price =(float)modelPro.getValueAt(row,2);
              float  Saleprice =(float)modelPro.getValueAt(row,3);
              Integer quantity=(Integer)modelPro.getValueAt(row,4);
              ipnProductID.setText(productID+"");
              ipnPrice.setText(Price+"");

        // TODO add your handling code here:
    }//GEN-LAST:event_productTblMouseClicked

    /**
     * @param args the command line arguments
     */
   
   private float tinhtongTien(int iQuantity, Float iPrice, Float iSaleOff,boolean  action){
   
       if(action){
           Tongtien =iQuantity*(iPrice-iSaleOff);
       }
       else {
           Tongtien=iQuantity*(iPrice-iSaleOff);
       }   
       return Tongtien;
    } 
   private float TotalOrder(){
       Integer OrderID=Integer.parseInt(ipnorderID.getText());
      
       float Total=Float.parseFloat(ipnTotal.getText());
       for(OrderDetail od:orderDetails){
           if(od.getOrderID().equals(OrderID))
               Total+=od.money();
       }
       for(Order order:orders){
           if(order.getOrderID().equals(OrderID)){
               order.setTotalMoneyDouble(Total);}
           
       }
       fileController.updatelistOrderToFile("order.txt", orders);
       return Total;
   }
   public void setNullIPN(){
       ipnProductID.setText("");
       ipnPrice.setText("");
       ipnQuantity.setText("");
       ipnMoney.setText(0.0+"");
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField ipnCustomerID1;
    private javax.swing.JTextField ipnDate;
    private javax.swing.JTextField ipnMoney;
    private javax.swing.JTextField ipnPrice;
    private javax.swing.JTextField ipnProductID;
    private javax.swing.JTextField ipnQuantity;
    private javax.swing.JTextField ipnTotal;
    private javax.swing.JTextField ipnorderID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable orderDetailTbl;
    private javax.swing.JTable productTbl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

 private void ProductDisplay()
    {
        modelPro=(DefaultTableModel)productTbl.getModel();
         products=FileController.readProductFromFile("product.txt");
         for(product  a:products){
                modelPro.addRow(new Object[]{
                a.getmaSP(),a.getTenSP(),a.getGiaBan(),a.getGiamGia(),a.getSoLuong()
            });
            }
    }

    private void OrderDetailDisplay() {
       
        Integer orderID =Integer.parseInt(ipnorderID.getText().trim());
        System.out.println(orderID);
        model=(DefaultTableModel)orderDetailTbl.getModel();
        orderDetails=FileController.readOrderDetailFromFile("orderDetail.txt");
        for(OrderDetail a:orderDetails){
             if(a.getOrderID().equals(orderID))
            {
            model.addRow(new  Object[]{
               a.getProductID(),a.getQuantity(),a.money()
            });
            }
        }
                
    }
}
        
   



