/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.admin;

import controller.file;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modal.product;

/**
 *
 * @author NguyenVanSonIT
 */
public class ManagementProduct extends javax.swing.JFrame {

    private javax.swing.table.DefaultTableModel model;
    static DefaultTableModel tableModal;
    static List<product> listProduct = new ArrayList<product>();
    static file file ;
    
        public void increaseIndex(){
        int lastIndex = listProduct.get(listProduct.size()-1).getMaSP();
        Preferences prefs = Preferences.userRoot().node(this.getClass().getName());

        AtomicInteger autoinc = new AtomicInteger(prefs.getInt("autoincrement", lastIndex));

        idspField.setText(""+autoinc.incrementAndGet());
        idspField.setEnabled(false);
        prefs.putInt("autoincrement", autoinc.get());
    }
    public ManagementProduct() {
        initComponents();
        setLocationRelativeTo(null);
        tableModal = (DefaultTableModel) productTable.getModel();
        listProduct = file.readProductFromFile("product.txt");
        for(product item : listProduct){
            tableModal.addRow(new Object[]{
                item.getMaSP(), item.getTenSP(), item.getGiaBan(), item.getGiaMua(), item.getGiamGia(), item.getSoLuong()
            });
        }
        suajButton.setEnabled(false);
        xoajButton.setEnabled(false);
       increaseIndex();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        idsplabel = new java.awt.Label();
        idspField = new java.awt.TextField();
        tensplabel = new java.awt.Label();
        tenspField = new java.awt.TextField();
        giamualabel = new java.awt.Label();
        giamuaField = new java.awt.TextField();
        giabanlabel = new java.awt.Label();
        giabanField = new java.awt.TextField();
        giagiamlabel = new java.awt.Label();
        giagiamField = new java.awt.TextField();
        soluonglabel = new java.awt.Label();
        soluongField = new java.awt.TextField();
        themjButton = new javax.swing.JButton();
        suajButton = new javax.swing.JButton();
        xoajButton = new javax.swing.JButton();
        trovejButton = new javax.swing.JButton();
        showloi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Giá Bán", "GIá Mua", "Giám Giãm", "Số Lượng"
            }
        ));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 123, 236));
        jLabel2.setText("QUẢN LÝ SẢN PHẨM");

        idsplabel.setText("Mã Sản Phẩm");

        idspField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idspFieldActionPerformed(evt);
            }
        });

        tensplabel.setText("Tên Sản Phẩm");

        giamualabel.setText("Giá Mua");

        giamuaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giamuaFieldActionPerformed(evt);
            }
        });

        giabanlabel.setText("Giá Bán");

        giagiamlabel.setText("Giảm Giá");

        giagiamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giagiamFieldActionPerformed(evt);
            }
        });

        soluonglabel.setText("Số Lượng");

        themjButton.setText("Thêm");
        themjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themjButtonActionPerformed(evt);
            }
        });

        suajButton.setText("Sửa");
        suajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suajButtonActionPerformed(evt);
            }
        });

        xoajButton.setText("Xóa");
        xoajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoajButtonActionPerformed(evt);
            }
        });

        trovejButton.setText("Trở Về ");
        trovejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trovejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(554, 554, 554)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soluonglabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giamualabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showloi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(giamuaField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soluongField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(giabanField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(giagiamField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tenspField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idsplabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(giabanlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(giagiamlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tensplabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idspField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(themjButton)
                        .addGap(242, 242, 242)
                        .addComponent(suajButton)
                        .addGap(237, 237, 237)
                        .addComponent(xoajButton)
                        .addGap(140, 140, 140)
                        .addComponent(trovejButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idsplabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idspField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tensplabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tenspField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(giabanlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(giabanField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(giamualabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(giamuaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(giagiamlabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(giagiamField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(soluonglabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(soluongField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showloi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themjButton)
                    .addComponent(suajButton)
                    .addComponent(xoajButton)
                    .addComponent(trovejButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themjButtonActionPerformed
        try {
            Integer maSP = Integer.parseInt(idspField.getText().trim());
            String tenSP = tenspField.getText().trim();
            Float giaBan = Float.parseFloat(giabanField.getText().trim());  
            Float giaMua = Float.parseFloat(giamuaField.getText().trim());
            Float giaGiam = Float.parseFloat(giagiamField.getText().trim());
            Integer soLuong = Integer.parseInt(soluongField.getText().trim());

            if(maSP.equals("") || tenSP.equals("") || giaBan.equals("") || giaMua.equals("") || giaGiam.equals("") || soLuong.equals("")) {
                showloi.setText("Vui lòng lòng nhập đầy đủ thông tin");
            }
            showloi.setText("");
             product Product = new product(maSP, tenSP, giaBan,giaMua ,giaGiam,soLuong);
     
            boolean check = false;
            if(check == false) {
                file.writeProductToFile("product.txt", Product);
                tableModal.addRow(new Object[]{
                    Product.getMaSP(), Product.getTenSP(), Product.getGiaBan(), Product.getGiaMua(), Product.getGiamGia(),Product.getSoLuong()
                                                });
                listProduct.add(Product);
            setTextNull("Thêm sản phẩm mới thành công", "Thêm mới sản phẩm");
              increaseIndex();
                //JOptionPane.showConfirmDialog(null, "Thêm tài san phâm mới thành công", "Thêm mới", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }
        } catch(NumberFormatException e) {
            showloi.setText("Vui lòng lòng nhập đầy đủ thông tin");
        } catch (Exception e) {
            showloi.setText("Vui lòng lòng nhập đầy đủ thông tin");
            showloi.setText(e.toString());
        }
    }//GEN-LAST:event_themjButtonActionPerformed

    private void xoajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoajButtonActionPerformed
        // TODO add your handling code here:
        int row = productTable.getSelectedRow();
        tableModal.removeRow(row);
        listProduct.remove(row);
        file.updateListProductToFile("product.txt", listProduct);
        suajButton.setEnabled(false);
        xoajButton.setEnabled(false);
        themjButton.setEnabled(true);
        setTextNull("Xóa thành công", "Xóa sản phẩm");
    }//GEN-LAST:event_xoajButtonActionPerformed

    private void trovejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trovejButtonActionPerformed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_trovejButtonActionPerformed

    private void suajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suajButtonActionPerformed
        // TODO add your handling code here:
            Integer maSP = Integer.parseInt(idspField.getText().trim());
            String tenSP = tenspField.getText().trim();
            Float giaBan = Float.parseFloat(giabanField.getText().trim());  
            Float giaMua = Float.parseFloat(giamuaField.getText().trim());
            Float giamGia = Float.parseFloat(giagiamField.getText().trim());
            Integer soLuong = Integer.parseInt(soluongField.getText().trim());
            int row = productTable.getSelectedRow();

        // update data in file
       product product = new product(maSP, tenSP, giaBan, giaMua, giamGia, soLuong);
        listProduct.set(row, product);
        file.updateListProductToFile("product.txt", listProduct);

        //update UI
        productTable.setValueAt(maSP, row, 0);
        productTable.setValueAt(tenSP, row, 1);
        productTable.setValueAt(giaBan, row, 2);
        productTable.setValueAt(giaMua, row, 3);
        productTable.setValueAt(giamGia, row, 4);
        productTable.setValueAt(soLuong, row, 5);

        suajButton.setEnabled(false);
        xoajButton.setEnabled(false);
        themjButton.setEnabled(true);
        setTextNull("Cập nhật thông tin thành công", "Cập nhật sản phẩm");
       increaseIndex();
    }//GEN-LAST:event_suajButtonActionPerformed

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
    int row = productTable.getSelectedRow();
    
        Integer maSP = (Integer) tableModal.getValueAt(row, 0);
        String tenSP = (String) tableModal.getValueAt(row, 1);
        Float giaBan = (Float) tableModal.getValueAt(row, 2);
        Float giaMua = (Float) tableModal.getValueAt(row, 3);
        Float giamGia = (Float) tableModal.getValueAt(row,4);
        Integer soLuong = (Integer) tableModal.getValueAt(row, 5);
        

        idspField.setText("" + maSP);
        tenspField.setText(tenSP);
        giabanField.setText("" + giaBan);
        giamuaField.setText("" + giaMua);
        giagiamField.setText("" + giamGia);
        soluongField.setText("" + soLuong);       
        

        idspField.setEnabled(false);
        themjButton.setEnabled(false);
        suajButton.setEnabled(true);
        xoajButton.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_productTableMouseClicked

    private void idspFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idspFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idspFieldActionPerformed

    private void giagiamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giagiamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giagiamFieldActionPerformed

    private void giamuaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giamuaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giamuaFieldActionPerformed
    private void setTextNull(String title, String subTitle){
        idspField.setText("" );
        tenspField.setText("");
        giabanField.setText("");
        giamuaField.setText("");
        giagiamField.setText("");
        soluongField.setText(""); 
        JOptionPane.showConfirmDialog(null, title, subTitle, JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField giabanField;
    private java.awt.Label giabanlabel;
    private java.awt.TextField giagiamField;
    private java.awt.Label giagiamlabel;
    private java.awt.TextField giamuaField;
    private java.awt.Label giamualabel;
    private java.awt.TextField idspField;
    private java.awt.Label idsplabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    private javax.swing.JLabel showloi;
    private java.awt.TextField soluongField;
    private java.awt.Label soluonglabel;
    private javax.swing.JButton suajButton;
    private java.awt.TextField tenspField;
    private java.awt.Label tensplabel;
    private javax.swing.JButton themjButton;
    private javax.swing.JButton trovejButton;
    private javax.swing.JButton xoajButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the model
     */
    public javax.swing.table.DefaultTableModel getModel() {
        return model;
    }

    /**
     * @param model the model to set
     */
    public void setModel(javax.swing.table.DefaultTableModel model) {
        this.model = model;
    }
}
